//! Complete world state. Plain data plus small, local invariants; the systems
//! that evolve it live in `pw-sim`.

pub mod academy;
pub mod affairs;
pub mod agenda;
pub mod agent;
pub mod almanac;
pub mod awards;
pub mod backfill;
pub mod beliefs;
pub mod calendar;
pub mod careers;
pub mod club;
pub mod commerce;
pub mod comp;
pub mod contract;
pub mod culture;
pub mod deals;
pub mod decision;
pub mod dressing;
pub mod ecosystem;
pub mod event;
pub mod ext;
pub mod evolution;
pub mod governance;
pub mod growth;
pub mod history;
pub mod honours;
pub mod inbox;
pub mod incident;
pub mod info;
pub mod intent;
pub mod interaction;
pub mod intl;
pub mod knowledge;
pub mod life;
pub mod matchfacts;
pub mod media;
pub mod medical;
pub mod minor;
pub mod names;
pub mod nation;
pub mod negotiation;
pub mod officials;
pub mod perf;
pub mod person;
pub mod player;
pub mod pressroom;
pub mod records;
pub mod ruling;
pub mod renown;
pub mod rules;
pub mod scouting;
pub mod social;
pub mod socialnet;
pub mod staff;
pub mod stafflife;
pub mod training;
pub mod stats;
pub mod world;
pub mod youth;

pub use club::{Club, Team, TeamKind};
pub use comp::{CompKind, Competition, Fixture, Fixtures, Format, Score, TableRow};
pub use contract::{Contract, ContractKind, Loan, SquadStatus};
pub use decision::{Choice, Decision, DecisionKind, Decisions, MindKind};
pub use event::{Cause, Causes, Event, EventKind, EventLog, Fact, LifeEventKind, Visibility};
pub use intent::{Intent, PartnerAsk};
pub use interaction::{Meeting, MeetingState, Outcome, Tone, Topic};
pub use life::{Life, Lifestyle, MoodFactor, Occupation, Routine};
pub use media::{FanReason, Story, StoryKind};
pub use names::{NameId, Names};
pub use nation::{Confed, Nation};
pub use negotiation::{Negotiation, TalkEnd, TalkKind, TalkLine, TalkState, Terms};
pub use person::Person;
pub use player::{Focus, Intensity, PlayerCold, PlayerHot, PlayerStatus, Players, TrainingPlan};
pub use social::{MemoryKind, Promise, PromiseKind, PromiseState, Rel, Social};
pub use staff::{Archetype, Philosophy, Staff, StaffRole};
pub use world::World;

pub type FxHashMap<K, V> = rustc_hash::FxHashMap<K, V>;
pub type FxHashSet<K> = rustc_hash::FxHashSet<K>;
