//! Where imported facts came from, and which facts the game filled in itself.
//!
//! Imported people, clubs, competitions and nations keep a reference to their source record. For each
//! imported person every group of facts is labelled: read from the source, derived from source values by a
//! documented rule, or generated from the world seed. People created by the game later (regens, staff hired to
//! fill gaps) have no entry, which means "generated by the game". Nothing here influences the simulation; it
//! is what lets the interface say "estimated" and what keeps imported data distinguishable.

use pw_core::{ClubId, CompId, Date, NationId, PersonId};
use rustc_hash::FxHashMap;
use serde::{Deserialize, Serialize};

#[derive(Clone, Copy, PartialEq, Eq, Hash, Debug, Serialize, Deserialize)]
pub enum Origin {
    /// Read from the source record.
    Imported,
    /// Derived from imported values by a documented rule.
    Inferred,
    /// Drawn from the world seed because the source had no value.
    Generated,
    /// The source had no value and the world holds only a placeholder; show it as unknown.
    Unknown,
}

impl Origin {
    pub const fn label(self) -> &'static str {
        match self {
            Origin::Imported => "imported",
            Origin::Inferred => "estimated from imported data",
            Origin::Generated => "generated",
            Origin::Unknown => "not known",
        }
    }
}

/// Club facts the source did not state and the importer filled in (bit set in `OriginBook::club_gaps`).
pub mod gap {
    pub const CITY: u16 = 1;
    pub const COLOURS: u16 = 2;
    pub const FOUNDED: u16 = 4;
    pub const FINANCES: u16 = 8;
    pub const FACILITIES: u16 = 16;
    pub const CAPACITY: u16 = 32;
    pub const STADIUM: u16 = 64;
    pub const REPUTATION: u16 = 128;
    pub const YOUTH_SIDES: u16 = 256;
}

/// A group of facts that share one origin.
#[derive(Clone, Copy, PartialEq, Eq, Hash, Debug, Serialize, Deserialize)]
#[repr(u8)]
pub enum Facet {
    Identity,
    Position,
    Attributes,
    Hidden,
    Potential,
    Contract,
    Value,
    Reputation,
    Physique,
    Career,
    Club,
}

pub const N_FACETS: usize = 11;

impl Facet {
    pub const ALL: [Facet; N_FACETS] =
        [Facet::Identity, Facet::Position, Facet::Attributes, Facet::Hidden, Facet::Potential, Facet::Contract, Facet::Value, Facet::Reputation, Facet::Physique, Facet::Career, Facet::Club];

    pub const fn label(self) -> &'static str {
        match self {
            Facet::Identity => "Identity",
            Facet::Position => "Position",
            Facet::Attributes => "Attributes",
            Facet::Hidden => "Personality",
            Facet::Potential => "Potential",
            Facet::Contract => "Contract",
            Facet::Value => "Value",
            Facet::Reputation => "Reputation",
            Facet::Physique => "Build",
            Facet::Career => "Career record",
            Facet::Club => "Club",
        }
    }
}

/// A source record: which source, and the record's own id (`player:10`).
#[derive(Clone, PartialEq, Eq, Hash, Debug, Serialize, Deserialize)]
pub struct SourceRef {
    pub source: u8,
    pub id: String,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct Source {
    pub name: String,
    /// When the data was captured, when the source says so.
    pub snapshot: Option<Date>,
    pub note: String,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct PersonOrigin {
    pub src: SourceRef,
    pub marks: [Origin; N_FACETS],
}

impl PersonOrigin {
    pub fn new(src: SourceRef) -> Self {
        Self { src, marks: [Origin::Imported; N_FACETS] }
    }

    pub fn mark(&mut self, facet: Facet, origin: Origin) {
        self.marks[facet as usize] = origin;
    }

    pub fn get(&self, facet: Facet) -> Origin {
        self.marks[facet as usize]
    }
}

/// A source row the importer could not place safely. It is kept, not guessed at.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct Unresolved {
    pub source: u8,
    pub id: String,
    pub what: String,
    pub reason: String,
}

/// Version of the provenance model an import writes (recorded in save metadata, §10.15).
pub const PROVENANCE_VERSION: u32 = 1;

#[derive(Clone, Default, Serialize, Deserialize)]
pub struct OriginBook {
    pub sources: Vec<Source>,
    pub nations: FxHashMap<NationId, SourceRef>,
    pub comps: FxHashMap<CompId, SourceRef>,
    pub clubs: FxHashMap<ClubId, SourceRef>,
    /// Which club facts were filled in, per club (see [`gap`]).
    pub club_gaps: FxHashMap<ClubId, u16>,
    pub people: FxHashMap<PersonId, PersonOrigin>,
    /// `source:id` → person, for searching by source id.
    pub by_ref: FxHashMap<String, PersonId>,
    /// The first rows the importer could not place (capped); the total is in `unresolved_total`.
    pub unresolved: Vec<Unresolved>,
    pub unresolved_total: u32,
    /// Import findings by code (`unknown_club`, `bad_date`, ...), largest first.
    pub findings: Vec<(String, u32)>,
}

pub const MAX_UNRESOLVED_KEPT: usize = 2_000;

impl OriginBook {
    pub fn is_empty(&self) -> bool {
        self.sources.is_empty()
    }

    pub fn ref_key(&self, r: &SourceRef) -> String {
        format!("{}:{}", self.sources.get(usize::from(r.source)).map_or("?", |s| s.name.as_str()), r.id)
    }

    pub fn add_person(&mut self, person: PersonId, origin: PersonOrigin) {
        let key = self.ref_key(&origin.src);
        self.by_ref.insert(key, person);
        self.people.insert(person, origin);
    }

    pub fn person(&self, p: PersonId) -> Option<&PersonOrigin> {
        self.people.get(&p)
    }

    pub fn find(&self, source: &str, id: &str) -> Option<PersonId> {
        self.by_ref.get(&format!("{source}:{id}")).copied()
    }

    pub fn add_unresolved(&mut self, u: Unresolved) {
        self.unresolved_total += 1;
        if self.unresolved.len() < MAX_UNRESOLVED_KEPT {
            self.unresolved.push(u);
        }
    }

    /// Imported people whose `facet` has the given origin.
    pub fn count_facet(&self, facet: Facet, origin: Origin) -> usize {
        self.people.values().filter(|p| p.get(facet) == origin).count()
    }
}
