[package]
name = "pw-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "pathway-sim"
path = "src/main.rs"

[[bin]]
name = "pathway"
path = "src/play.rs"

[dependencies]
pw-core.workspace = true
pw-data.workspace = true
pw-world.workspace = true
pw-match.workspace = true
pw-sim.workspace = true
pw-import.workspace = true
pw-career.workspace = true
pw-narrate.workspace = true
